name: grabto
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.43

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  pod_player: ^0.2.2

  cupertino_icons: ^1.0.8
  http: ^1.2.2
  provider: ^6.1.2
  shared_preferences: ^2.3.5
  image_picker: ^1.1.2
  razorpay_flutter: ^1.3.7
  url_launcher: ^6.3.1
  intl: ^0.20.1
  carousel_slider: ^5.0.0
  cached_network_image: ^3.4.1
  package_info_plus:
  share_plus: ^10.1.4
  flutter_rating_bar: ^4.0.1
  smooth_page_indicator: ^1.2.0+3
  photo_view: ^0.15.0
  lottie: ^3.3.1
  loading_animation_widget: ^1.3.0
  firebase_core: ^3.10.0
  firebase_messaging: ^15.2.0
  youtube_player_flutter:
  iconly:
  lucide_icons:
  google_maps_flutter:
  geolocator: ^11.0.0
  geocoding:



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/
    - assets/gif/
    - assets/fonts/
    - assets/images/
    - assets/lottie/
    - assets/vector/

  fonts:
    - family: roboto
      fonts:
        - asset: assets/fonts/Roboto_Regular.ttf
    - family: metropolis
      fonts:
        - asset: assets/fonts/metropolis.light.otf
    - family: ubuntu
      fonts:
        - asset: assets/fonts/Ubuntu-MediumItalic.ttf
        - asset: assets/fonts/Ubuntu-Medium.ttf
        - asset: assets/fonts/Ubuntu-Regular.ttf
        - asset: assets/fonts/Ubuntu-Bold.ttf
        - asset: assets/fonts/Ubuntu-BoldItalic.ttf
        - asset: assets/fonts/Ubuntu-Italic.ttf
        - asset: assets/fonts/Ubuntu-Light.ttf
        - asset: assets/fonts/Ubuntu-LightItalic.ttf
        - asset: assets/fonts/VastShadow-Regular.ttf

    - family: afacadFlux
      fonts:
        - asset: assets/fonts/AfacadFlux-Regular.ttf

    - family: vast
      fonts:
        - asset: assets/fonts/VastShadow-Regular.ttf


