// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAEYBCcraoPi6a0H5csvSlePUVg3IRCQC0',
    appId: '1:221735590820:web:6e229b71b2e21fe6d3bf31',
    messagingSenderId: '221735590820',
    projectId: 'grabto-a9d09',
    authDomain: 'grabto-a9d09.firebaseapp.com',
    storageBucket: 'grabto-a9d09.appspot.com',
    measurementId: 'G-XYW9W4Q0PF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDT0WCWoukgvALiSl0bp9J2LH1mTEyMjvI',
    appId: '1:221735590820:android:6a0f56b73541dc3ad3bf31',
    messagingSenderId: '221735590820',
    projectId: 'grabto-a9d09',
    storageBucket: 'grabto-a9d09.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqQXIvUec8o3CCGMtXVW2ZH0hm1RybEE0',
    appId: '1:221735590820:ios:2bf9ff725bacc1a0d3bf31',
    messagingSenderId: '221735590820',
    projectId: 'grabto-a9d09',
    storageBucket: 'grabto-a9d09.appspot.com',
    androidClientId: '221735590820-7l8rlfiosv90tr0dna4cf6bf4u87ajnh.apps.googleusercontent.com',
    iosBundleId: 'digi.coders.discountDeals.discountDeals',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCqQXIvUec8o3CCGMtXVW2ZH0hm1RybEE0',
    appId: '1:221735590820:ios:2bf9ff725bacc1a0d3bf31',
    messagingSenderId: '221735590820',
    projectId: 'grabto-a9d09',
    storageBucket: 'grabto-a9d09.appspot.com',
    androidClientId: '221735590820-7l8rlfiosv90tr0dna4cf6bf4u87ajnh.apps.googleusercontent.com',
    iosBundleId: 'digi.coders.discountDeals.discountDeals',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAEYBCcraoPi6a0H5csvSlePUVg3IRCQC0',
    appId: '1:221735590820:web:27004a4deb009b0fd3bf31',
    messagingSenderId: '221735590820',
    projectId: 'grabto-a9d09',
    authDomain: 'grabto-a9d09.firebaseapp.com',
    storageBucket: 'grabto-a9d09.appspot.com',
    measurementId: 'G-EQ0STSHXRE',
  );

}